# Page settings

baseURL = "https://a3ventures.dev/"
languageCode = "en"
title = "Alexander Ackerman Resume"
theme = "DevResume"
googleAnalytics = "UA-XXXXXXX-Y"
publishDir = "docs"


[params]
    author = "Alexander Ackerman"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"

    primaryColor = "#90cc1a" 
    textPrimaryColor = "#292929"


    [params.profile]
        enable = true
        name = "Alexander Ackerman"
        #tagline = "May 2021 Bachelor's of Computer Science Graduate"
        avatar = "headshot.png"


    [params.contact]
        enable = true
        location = "Vancouver, BC, Canada"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:+17789037178"
        text = "+1 778 903 7178"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:alex@a3ventures.dev"
        text = "alex@a3ventures.dev"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://a3ventures.dev"
        text = "a3ventures.dev"
        [[params.contact.list]]
        icon = "fab fa-github-square"
        url = "//github.com/a3ackerman"
        text = "A3Ackerman"
        [[params.contact.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/alexander-ackerman-8419464b"
        text = "Alexander Ackerman"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Languages & Libraries"
        [[params.skills.list.items]]
        details = "Python"
        [[params.skills.list.items]]
        details = "Typescript"
        [[params.skills.list.items]]
        details = "JavaScript, Node.js, Vue, React"
         [[params.skills.list.items]]
        details = "Bash"
        [[params.skills.list.items]]
        details = "PostgreSQL, MySQL"
        [[params.skills.list.items]]
        details = "Java including Javac tools"
        [[params.skills.list.items]]
        details = "C and C++ from school"
        [[params.skills.list.items]]
        details = "RFC 2119 compliant design & documentation"

        [[params.skills.list]]
        title = "Dev Ops Tools"
        [[params.skills.list.items]]
        details = "Docker"
        [[params.skills.list.items]]
        details = "Kubernetes"
        [[params.skills.list.items]]
        details = "Helm 2 & 3"
        [[params.skills.list.items]]
        details = "Open Nebula"
        [[params.skills.list.items]]
        details = "Sensu Core"


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Bachelor of Computer Science"
        university = "University of British Columbia" # | 2018 - 2021"
        dates = "2018 - 2021"
        gpa = "GPA: A"
        [[params.education.list.items]]
        details = "Graduating May 2021, GPA: A"
        [[params.education.list.items]]
        details = "Specialization: statistics and data science"
        [[params.education.list.items]]
        details = "Teaching Assistant for Computer Science 100 and 200 level courses"

        # [[params.education.list]]
        # degree = "BA Honours Economics & Finance"
        # university = "McGill University" # | 2010 - 2014"
        # dates = "2010 - 2014"


    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Jim McCollum Award for Innovation"
        body = "An award given by the Soaring Association of Canada recognizing my efforts to promote soaring among youth and younger adults, including fundraising efforts for the non-profit Youth Flight Canada"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"




    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "French"
        level = "Conversational"
        [[params.languages.list]]
        name = "Spanish"
        level = "Basic"



    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Soaring/Flying Sailplanes"
        [[params.interests.list]]
        name = "Skiing"
        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Cooking"
        [[params.interests.list]]
        name = "Guitar & singing"



    [params.summary]
        enable = false
        text = 'I love studying complex systems and trying to understand how they work, be they markets, cloud native technologies, or weather systems (just for fun). I am currently seeking opportunties to learn and tackle fresh problems.'
        work_status = true

[params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Engineering Intern"
        dates = "2020"
        company = "[Demonware (Activision Blizzard)](https://demonware.net/)"
        [[params.experience.list.items]]
        details = "Completed a data analytics project using Little's Law to estimate required deployment sizes needed to serve Call of Duty Warzone's 50 million+ players. Estimates led to reducing CPU resource allocations, creating savings of approx $100k"
        [[params.experience.list.items]]
        details = "Also worked with the monitoring stack, which monitored all Demonware services for proper functioning, and would Slack and/or page the right engineers if their service malfunctioned"
        [[params.experience.list.items]]
        details = "Designed, built and deployed a back-end Python micro-services to Kubernetes from end-to-end which was used to test that new checks/alerts were configured correctly and properly routed by the monitoring stack"
        [[params.experience.list.items]]
        details = "Developed and released an upstream Helm chart (a GoLang Template) which allowed internal customers to easily add a monitoring agent to their Kubernetes deployments, saving at least 2-3 hours of developer work for deploying any new service"
       
        [[params.experience.list]]
        title = "Lead SDR & Digital Marketing Specialist"
        dates = "2018 - 2019"
        company = "[Venzee](https://www.venzee.com/)"
        [[params.experience.list.items]]
        details = "Venzee is a SaaS startup working to automate the E-commerce product data supply chain"
        [[params.experience.list.items]]
        details = "Led a team of 8 Sales Dev Reps, including supporting their sales training and skill development"
        [[params.experience.list.items]]
        details = "Wrote Python scripts using BeautifulSoup used to collect, process, and score 50k leads leading to a 5% improvement in our demo-booking rate"
        [[params.experience.list.items]]
        details = "Planned and executed several projects to clean and organize our sales and marketing data from Hubspot and other sources"
        [[params.experience.list.items]]
        details = "Ran a content marketing campaign to improve Venzee's SEO for high value keywords"

        # [[params.experience.list]]
        # title = "Founder"
        # dates = "2016 - Present"
        # company = "[A3 Ventures](https://a3ventures.dev/)"
        # [[params.experience.list.items]]
        # details = "A3 Ventures is my personal tradename/brand (my initials are AAA) under which I have done some consulting work for a few clients"
        # [[params.experience.list.items]]
        # details = "Services include investment research (loose focus on the life science industry) and building a B2B lead generation database for a small industrial business"
        

        # [[params.experience.list]]
        # title = "Project Director/Analyst"
        # dates = "2014 - 2017"
        # company = "[Focus Reports](https://www.linkedin.com/company/focusreports/about/)"
        # [[params.experience.list.items]]
        # details = "Wrote content for 10+ country specific editions of the [Healthcare & Life Science Review](https://pharmaboardroom.com/country-reports/), published on [PharmaBoardroom.com](https://pharmaboardroom.com/)"
        # [[params.experience.list.items]]
        # details = "Worked on and led small two and three person teams to conduct interviews and sell advertising"
        # [[params.experience.list.items]]
        # details = "Researched healthcare policies, biotech technology platforms, and pharma company business models in preparation for interviews with C-suite executives and to write published content"
        # [[params.experience.list.items]]
        # details = "Was responsible for revenue generation via advertising sales across the full sales funnel from lead generation via cold calls to closing. Best year was 2016 with over USD 500k in sales"



    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "[Tic Tac Toe Neural Network](https://github.com/A3Ackerman/TicTacToeNeuralNet)"
        meta = "In Progress"
        [[params.projects.list.items]]
        details = "A single layer neural network that classifies complete tic tac toe games by winner/draw"
        [[params.projects.list.items]]
        details = "Functional React front-end, with all ML calculations coded in raw Python with Numpy"
        [[params.projects.list.items]]
        details = "Python code ran within the users browser using Mozilla backed Pyodide (Python compiled to WebAssembly) - no back-end required!"
        
        
        # [[params.projects.list]]
        # title = "[EcoReview Chrome Extension](https://github.com/A3Ackerman/EcoReviewPlugin)"
        # [[params.projects.list.items]]
        # details = "A Google Chrome extension for crowdsourcing independent reviews of products that are marketed as being ecofriendly, but may not be in reality (aka \"greenwashing\")."
        # [[params.projects.list.items]]
        # details = "React front-end utilizes the Google Chrome API to obtain access to variables in user's currently active tab."
        # [[params.projects.list.items]]
        # details = "Backend consisted of a Python Flask webserver with MongoDB docker container."

        [[params.projects.list]]
        title = "[Java Dynamic Runtime Visualization](https://java-dragon-slaying.github.io/SolarSystemRuntimeAnalysis/)"
        [[params.projects.list.items]]
        details = "Developed a [Javac compiler plugin](https://github.com/Java-Dragon-Slaying/SolarSystemRuntimeAnalysis/blob/main/src/main/java/JavacPlugin.java) that modifies programs during the compilation process to log specific information we wish to visualize"


    [params.information]
        enable = false

        [[params.information.list]]
        title = ""
        [[params.information.list.items]]
        details = ""



    [params.social]
        enable = false

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/a3ackerman"
        title = "A3Ackerman"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/alexander-ackerman-8419464b"
        title = "Alexander Ackerman"
        #[[params.social.list]]
        #icon = "fab fa-twitter-square"
        #url = "https://twitter.com/Alex77696777"
        #title = "@Alex7769677"





